- copy: dest=/etc/mesos/zk content="{{ zk_config }}\n"
- copy: dest=/etc/mesos-slave/containerizers content="docker,mesos"
  notify: restart mesos-slave
- service: name={{ item }} state=started
  with_items:
  - mesos-slave
